language: python
install: pip install tox coveralls
matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=pylint
    - python: 3.5
      env: TOXENV=py35-cover
script: tox
after_success: coveralls
